export const GET_USER_SUBCRIPTION_REQUEST = "GET_USER_SUBCRIPTION_REQUEST";
export const GET_USER_SUBCRIPTION_SUCCESS = "GET_USER_SUBCRIPTION_SUCCESS";
export const GET_USER_SUBCRIPTION_FAILURE = "GET_USER_SUBCRIPTION_FAILURE";

export const UPGRADE_SUBCRIPTION_REQUEST = "UPGRADE_SUBCRIPTION_REQUEST";
export const UPGRADE_SUBCRIPTION_SUCCESS = "UPGRADE_SUBCRIPTION_SUCCESS";
export const UPGRADE_SUBCRIPTION_FAILURE = "UPGRADE_SUBCRIPTION_FAILURE";
